import * as github from "@actions/github";
import { Symbol } from "./extract";
import { Classification, formatClassification } from "./classify";

const COMMENT_HEADER = "<!-- xray-arch-diff -->";

function formatSymbols(symbols: Symbol[]): string {
  const added = symbols.filter((s) => s.change === "added");
  const removed = symbols.filter((s) => s.change === "removed");

  if (added.length === 0 && removed.length === 0) {
    return "_No structural symbol changes detected._";
  }

  const lines: string[] = [];

  for (const s of added) {
    lines.push(`+ ${s.name.padEnd(30)} (new ${s.kind})`);
  }
  for (const s of removed) {
    lines.push(`- ${s.name.padEnd(30)} (removed ${s.kind})`);
  }

  return lines.join("\n");
}

function formatFilesSummary(
  newFiles: string[],
  deletedFiles: string[],
  totalChanged: number
): string {
  const parts: string[] = [`**${totalChanged}** files changed`];
  if (newFiles.length > 0) parts.push(`**${newFiles.length}** new`);
  if (deletedFiles.length > 0) parts.push(`**${deletedFiles.length}** deleted`);
  return parts.join(" · ");
}

export function composeComment(
  classification: Classification,
  symbols: Symbol[],
  newFiles: string[],
  deletedFiles: string[],
  totalFiles: number,
  linesAdded: number,
  linesRemoved: number,
  diagram: string | null
): string {
  const sections: string[] = [COMMENT_HEADER, "## xray — architecture diff", ""];

  sections.push(
    formatFilesSummary(newFiles, deletedFiles, totalFiles) +
      ` · **+${linesAdded}** / **-${linesRemoved}**`
  );
  sections.push("");

  const classStr = formatClassification(classification);
  if (classStr) {
    sections.push("### Change classification");
    sections.push("```");
    sections.push(classStr);
    sections.push("```");
    sections.push("");
  }

  sections.push("### Structural changes");
  sections.push("```diff");
  sections.push(formatSymbols(symbols));
  sections.push("```");
  sections.push("");

  if (newFiles.length > 0) {
    sections.push("<details><summary>New files</summary>");
    sections.push("");
    for (const f of newFiles) {
      sections.push(`- \`${f}\``);
    }
    sections.push("");
    sections.push("</details>");
    sections.push("");
  }

  if (diagram) {
    sections.push("### Dependency diagram");
    sections.push("```mermaid");
    sections.push(diagram);
    sections.push("```");
    sections.push("");
  }

  sections.push(
    "<sub>generated by [xray](https://github.com/kasrakhosravi/xray) — deterministic architecture diffs</sub>"
  );

  return sections.join("\n");
}

export async function postComment(
  token: string,
  body: string
): Promise<void> {
  const octokit = github.getOctokit(token);
  const ctx = github.context;

  if (!ctx.payload.pull_request) {
    return;
  }

  const prNumber = ctx.payload.pull_request.number;
  const repo = ctx.repo;

  const { data: comments } = await octokit.rest.issues.listComments({
    ...repo,
    issue_number: prNumber,
    per_page: 100,
  });

  const existing = comments.find(
    (c) => c.body?.includes(COMMENT_HEADER)
  );

  if (existing) {
    await octokit.rest.issues.updateComment({
      ...repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      ...repo,
      issue_number: prNumber,
      body,
    });
  }
}
