import * as core from "@actions/core";
import * as github from "@actions/github";
import { Symbol, FileSummary } from "./extract";
import { Classification, formatClassification } from "./classify";

const COMMENT_HEADER = "<!-- xray-arch-diff -->";

function formatSymbols(symbols: Symbol[]): string {
  const added = symbols.filter((s) => s.change === "added");
  const removed = symbols.filter((s) => s.change === "removed");

  if (added.length === 0 && removed.length === 0) {
    return "_No structural symbol changes detected._";
  }

  const seen = new Set<string>();
  const modified: Symbol[] = [];
  const pureAdded: Symbol[] = [];
  const pureRemoved: Symbol[] = [];

  for (const s of added) {
    if (removed.some((r) => r.name === s.name && r.kind === s.kind)) {
      if (!seen.has(`${s.name}:${s.kind}`)) {
        modified.push({ ...s, change: "added" });
        seen.add(`${s.name}:${s.kind}`);
      }
    } else {
      pureAdded.push(s);
    }
  }
  for (const s of removed) {
    if (!added.some((a) => a.name === s.name && a.kind === s.kind)) {
      pureRemoved.push(s);
    }
  }

  const lines: string[] = [];
  for (const s of pureAdded) {
    lines.push(`+ ${s.name.padEnd(35)} (new ${s.kind})`);
  }
  for (const s of modified) {
    lines.push(`~ ${s.name.padEnd(35)} (modified ${s.kind})`);
  }
  for (const s of pureRemoved) {
    lines.push(`- ${s.name.padEnd(35)} (removed ${s.kind})`);
  }

  return lines.join("\n");
}

function formatFileRanking(fileSummaries: FileSummary[]): string {
  const nonTest = fileSummaries.filter((f) => !f.isTest && f.symbols.length > 0);
  const testFiles = fileSummaries.filter((f) => f.isTest);

  if (nonTest.length === 0 && testFiles.length === 0) return "";

  const lines: string[] = [];
  let rank = 1;

  for (const f of nonTest) {
    const kindParts = Object.entries(f.symbolsByKind)
      .map(([k, v]) => `${v} ${k}`)
      .join(", ");
    const label = f.isNew ? " (new)" : "";
    lines.push(
      `${String(rank).padStart(2)}. ${f.file}${label}  — +${f.linesAdded}/-${f.linesRemoved}, ${kindParts}`
    );
    rank++;
  }

  if (testFiles.length > 0) {
    const totalTestLines = testFiles.reduce((sum, f) => sum + f.linesAdded, 0);
    lines.push(
      `${String(rank).padStart(2)}. ${testFiles.length} test file${testFiles.length > 1 ? "s" : ""}  — +${totalTestLines} lines (verify after reviewing above)`
    );
  }

  return lines.join("\n");
}

function formatFilesSummary(
  newFiles: string[],
  deletedFiles: string[],
  totalChanged: number
): string {
  const parts: string[] = [`**${totalChanged}** files changed`];
  if (newFiles.length > 0) parts.push(`**${newFiles.length}** new`);
  if (deletedFiles.length > 0) parts.push(`**${deletedFiles.length}** deleted`);
  return parts.join(" · ");
}

export function composeComment(
  classification: Classification,
  symbols: Symbol[],
  fileSummaries: FileSummary[],
  newFiles: string[],
  deletedFiles: string[],
  totalFiles: number,
  linesAdded: number,
  linesRemoved: number,
  diagram: string | null
): string {
  const sections: string[] = [COMMENT_HEADER, "## xray — architecture diff", ""];

  const reviewLines = classification.logic;
  const testLines = classification.tests;
  let summary = formatFilesSummary(newFiles, deletedFiles, totalFiles) +
    ` · **+${linesAdded}** / **-${linesRemoved}**`;
  if (reviewLines > 0 && testLines > 0) {
    summary += `\n\n> **Review ~${reviewLines} lines of logic** — ${testLines} lines are tests`;
  } else if (reviewLines > 0) {
    summary += `\n\n> **Review ~${reviewLines} lines of logic**`;
  }
  sections.push(summary);
  sections.push("");

  const classStr = formatClassification(classification);
  if (classStr) {
    sections.push("<details><summary>Change classification</summary>");
    sections.push("");
    sections.push("```");
    sections.push(classStr);
    sections.push("```");
    sections.push("");
    sections.push("</details>");
    sections.push("");
  }

  sections.push("### Structural changes");
  sections.push("```diff");
  sections.push(formatSymbols(symbols));
  sections.push("```");
  sections.push("");

  const fileRanking = formatFileRanking(fileSummaries);
  if (fileRanking) {
    sections.push("### Files by change density");
    sections.push("```");
    sections.push(fileRanking);
    sections.push("```");
    sections.push("");
  }

  if (newFiles.length > 0) {
    sections.push("<details><summary>New files</summary>");
    sections.push("");
    for (const f of newFiles) {
      sections.push(`- \`${f}\``);
    }
    sections.push("");
    sections.push("</details>");
    sections.push("");
  }

  if (diagram) {
    sections.push("### Dependency diagram");
    sections.push("```mermaid");
    sections.push(diagram);
    sections.push("```");
    sections.push("");
  }

  sections.push(
    "<sub>generated by [xray](https://github.com/kasrakhosravi/xray) — deterministic architecture diffs</sub>"
  );

  return sections.join("\n");
}

export async function postComment(
  token: string,
  body: string
): Promise<void> {
  const octokit = github.getOctokit(token);
  const ctx = github.context;

  const prNumber =
    ctx.payload.pull_request?.number ?? ctx.payload.issue?.number;
  if (!prNumber) {
    core.warning("Could not determine PR number. Skipping comment.");
    return;
  }

  const repo = ctx.repo;

  const { data: comments } = await octokit.rest.issues.listComments({
    ...repo,
    issue_number: prNumber,
    per_page: 100,
  });

  const existing = comments.find(
    (c) => c.body?.includes(COMMENT_HEADER)
  );

  if (existing) {
    await octokit.rest.issues.updateComment({
      ...repo,
      comment_id: existing.id,
      body,
    });
  } else {
    await octokit.rest.issues.createComment({
      ...repo,
      issue_number: prNumber,
      body,
    });
  }
}
